In [1]:
from datetime import date
import hisepy
import os
import polars as pl
import re

In [2]:
if not os.path.isdir('output'):
    os.mkdir('output')

In [3]:
out_files = []

## Helper functions

In [4]:
def element_id(n = 3):
    import periodictable
    from random import randrange
    rand_el = []
    for i in range(n):
        el = randrange(0,118)
        rand_el.append(periodictable.elements[el].name)
    rand_str = '-'.join(rand_el)
    return rand_str

## Input files stored in HISE

In [5]:
in_uuids = {
    'deg': 'a134530f-9ac4-4d37-bf01-97c73bf1ce24', # RNA: Differentially Expressed Genes
    'hallmark': '4f05f2a0-59d2-4d04-b948-70d541613e71', #RNA: Hallmark Gene Set Enrichment Analysis results
    'reactome': 'ad8d7320-399c-41ff-8b2f-b840d8eae324', #RNA: Reactome Gene Set Enrichment Analysis results
    'dap': '681e1f11-708c-4ab4-8ed0-87ef895df152', # ATAC: Differentially Accessible Peaks
    'dam': 'ad10c6d0-0aad-490f-a82c-6bf7ce67cd58', # ATAC: Differentially Accessible Motifs
    'dep': '38b59e4a-3c87-460d-b3e2-fd5ed62e7264', # ADT: Differentially Expressed Proteins
    'dgm': '06039bda-26a0-4a51-85b4-f2b5aedcdf74'  # RNA + ATAC: DEG Gene Motifs
}

In [6]:
in_files = {}
for k, uuid in in_uuids.items():
    in_files[k] = hisepy.cache_files([uuid])[0]

2026-06-15 21:26:57,348 INFO [hisepy.logging:175] logging 14664 139138472589120 Calling cache_files
2026-06-15 21:27:03,266 INFO [hisepy.logging:208] logging 14664 139138472589120 Finished cache_files, success=True, time_elapsed=3.952s
2026-06-15 21:27:03,267 INFO [hisepy.logging:175] logging 14664 139138472589120 Calling cache_files
2026-06-15 21:27:07,620 INFO [hisepy.logging:208] logging 14664 139138472589120 Finished cache_files, success=True, time_elapsed=2.862s
2026-06-15 21:27:07,621 INFO [hisepy.logging:175] logging 14664 139138472589120 Calling cache_files
2026-06-15 21:27:12,125 INFO [hisepy.logging:208] logging 14664 139138472589120 Finished cache_files, success=True, time_elapsed=2.966s
2026-06-15 21:27:12,125 INFO [hisepy.logging:175] logging 14664 139138472589120 Calling cache_files
2026-06-15 21:27:16,274 INFO [hisepy.logging:208] logging 14664 139138472589120 Finished cache_files, success=True, time_elapsed=2.756s
2026-06-15 21:27:16,274 INFO [hisepy.logging:175] logging 14664 139138472589120 Calling cache_files
2026-06-15 21:27:20,615 INFO [hisepy.logging:208] logging 14664 139138472589120 Finished cache_files, success=True, time_elapsed=2.770s
2026-06-15 21:27:20,616 INFO [hisepy.logging:175] logging 14664 139138472589120 Calling cache_files
2026-06-15 21:27:24,721 INFO [hisepy.logging:208] logging 14664 139138472589120 Finished cache_files, success=True, time_elapsed=2.679s
2026-06-15 21:27:24,722 INFO [hisepy.logging:175] logging 14664 139138472589120 Calling cache_files
2026-06-15 21:27:29,048 INFO [hisepy.logging:208] logging 14664 139138472589120 Finished cache_files, success=True, time_elapsed=2.776s

In [7]:
cell_type_update = {
    "t_cd4_cm": "CD4 CM",
    "t_cd4_em": "CD4 EM",
    "t_cd4_naive": "CD4 Naive",
    "t_cd4_treg": "CD4 Treg",
    "t_cd8_memory": "CD8 Memory",
    "t_cd8_naive": "CD8 Naive"
}
treatment_update = {
    "bortezomib": "Bortezomib",
    "dexamethasone": "Dexamethasone",
    "dmso": "DMSO",
    "lenalidomide": "Lenalidomide",
    "untreated": "Untreated"
}
timepoint_update = {
    "0": "T0",
    "4": "T4",
    "24": "T24",
    "72": "T72"
}

## DEGs

In [8]:
deg = pl.read_csv(in_files['deg'], infer_schema_length=100000)

In [9]:
deg.head()

shape: (5, 12)
┌──────────────┬───────────┬────────────┬──────┬───┬──────────────┬──────────┬──────────┬──────────┐
│ aifi_cell_ty ┆ timepoint ┆ fg         ┆ bg   ┆ … ┆ logFC        ┆ nomP     ┆ adjP     ┆ mean     │
│ pe           ┆ ---       ┆ ---        ┆ ---  ┆   ┆ ---          ┆ ---      ┆ ---      ┆ ---      │
│ ---          ┆ i64       ┆ str        ┆ str  ┆   ┆ str          ┆ f64      ┆ f64      ┆ f64      │
│ str          ┆           ┆            ┆      ┆   ┆              ┆          ┆          ┆          │
╞══════════════╪═══════════╪════════════╪══════╪═══╪══════════════╪══════════╪══════════╪══════════╡
│ t_cd4_cm     ┆ 4         ┆ bortezomib ┆ dmso ┆ … ┆ -0.008603940 ┆ 0.74037  ┆ 0.999237 ┆ 0.085197 │
│              ┆           ┆            ┆      ┆   ┆ 28790527     ┆          ┆          ┆          │
│ t_cd4_cm     ┆ 4         ┆ bortezomib ┆ dmso ┆ … ┆ -0.054295087 ┆ 0.145599 ┆ 0.991887 ┆ 0.29036  │
│              ┆           ┆            ┆      ┆   ┆ 46593        ┆          ┆          ┆          │
│ t_cd4_cm     ┆ 4         ┆ bortezomib ┆ dmso ┆ … ┆ 0.0148158042 ┆ 0.876254 ┆ 0.999237 ┆ 0.895006 │
│              ┆           ┆            ┆      ┆   ┆ 264956       ┆          ┆          ┆          │
│ t_cd4_cm     ┆ 4         ┆ bortezomib ┆ dmso ┆ … ┆ 0.0431354534 ┆ 0.160231 ┆ 0.991887 ┆ 0.2063   │
│              ┆           ┆            ┆      ┆   ┆ 815564       ┆          ┆          ┆          │
│ t_cd4_cm     ┆ 4         ┆ bortezomib ┆ dmso ┆ … ┆ -0.010012028 ┆ 0.733253 ┆ 0.999237 ┆ 0.068101 │
│              ┆           ┆            ┆      ┆   ┆ 0827752      ┆          ┆          ┆          │
└──────────────┴───────────┴────────────┴──────┴───┴──────────────┴──────────┴──────────┴──────────┘

In [10]:
deg = deg.with_columns(
    pl.Series(
        name = 'Cell Type',
        values = [cell_type_update[x] for x in deg['aifi_cell_type']]
    ),
    pl.Series(
        name = 'Timepoint',
        values = [timepoint_update[x] for x in deg['timepoint'].cast(pl.String)]
    ),
    pl.Series(
        name = 'Treatment',
        values = [treatment_update[x] for x in deg['fg']]
    ),
    pl.Series(
        name = 'fg',
        values = [treatment_update[x] for x in deg['fg']]
    ),
    pl.Series(
        name = 'bg',
        values = [treatment_update[x] for x in deg['bg']]
    ),
    pl.col('logFC').replace("NA", None).cast(pl.Float32),
    pl.col('nomP').cast(pl.Float32),
    pl.col('adjP').cast(pl.Float32)
).select(
    ['Cell Type', 'Treatment', 'Timepoint', 'fg', 'bg', 'gene',
     'n_sample', 'mean', 'logFC', 'nomP', 'adjP']
)

In [11]:
deg.head()

shape: (5, 11)
┌───────────┬────────────┬───────────┬────────────┬───┬──────────┬───────────┬──────────┬──────────┐
│ Cell Type ┆ Treatment  ┆ Timepoint ┆ fg         ┆ … ┆ mean     ┆ logFC     ┆ nomP     ┆ adjP     │
│ ---       ┆ ---        ┆ ---       ┆ ---        ┆   ┆ ---      ┆ ---       ┆ ---      ┆ ---      │
│ str       ┆ str        ┆ str       ┆ str        ┆   ┆ f64      ┆ f32       ┆ f32      ┆ f32      │
╞═══════════╪════════════╪═══════════╪════════════╪═══╪══════════╪═══════════╪══════════╪══════════╡
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.085197 ┆ -0.008604 ┆ 0.74037  ┆ 0.999237 │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.29036  ┆ -0.054295 ┆ 0.145599 ┆ 0.991887 │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.895006 ┆ 0.014816  ┆ 0.876254 ┆ 0.999237 │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.2063   ┆ 0.043135  ┆ 0.160231 ┆ 0.991887 │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.068101 ┆ -0.010012 ┆ 0.733253 ┆ 0.999237 │
└───────────┴────────────┴───────────┴────────────┴───┴──────────┴───────────┴──────────┴──────────┘

In [12]:
out_deg = 'output/tcell-vrd_deg_{d}.csv'.format(d = date.today())
deg.write_csv(out_deg)
out_files.append(out_deg)

## Hallmark GSEA

In [13]:
hallmark = pl.read_csv(in_files['hallmark'], infer_schema_length=100000)

In [14]:
hallmark.head()

shape: (5, 12)
┌────────────┬──────┬───────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ fg         ┆ bg   ┆ timepoint ┆ aifi_cell_ ┆ … ┆ n_leadingE ┆ n_pathway_ ┆ leadingEd ┆ pathway_g │
│ ---        ┆ ---  ┆ ---       ┆ type       ┆   ┆ dge        ┆ genes      ┆ ge        ┆ enes      │
│ str        ┆ str  ┆ i64       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│            ┆      ┆           ┆ str        ┆   ┆ i64        ┆ i64        ┆ str       ┆ str       │
╞════════════╪══════╪═══════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ bortezomib ┆ dmso ┆ 24        ┆ t_cd4_cm   ┆ … ┆ 180        ┆ 236        ┆ PSMD1;PSM ┆ ABCE1;ACP │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ D14;PSMB2 ┆ 1;AIMP2;A │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ ;PSMD7;PS ┆ P3S1;APEX │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ MA6…      ┆ 1;B…      │
│ bortezomib ┆ dmso ┆ 24        ┆ t_cd4_cm   ┆ … ┆ 142        ┆ 211        ┆ PSMD14;TX ┆ ABCF2;ACA │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ NRD1;PSMD ┆ CA;ACACA; │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ 12;PSMC6; ┆ ACLY;ACSL │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ SQS…      ┆ 3;A…      │
│ bortezomib ┆ dmso ┆ 24        ┆ t_cd4_cm   ┆ … ┆ 38         ┆ 58         ┆ TXNRD1;TX ┆ ABCC1;ABC │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ N;GSR;FTL ┆ C1;ATOX1; │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ ;PRDX1;GC ┆ CAT;CDKN2 │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ LM;…      ┆ D;E…      │
│ bortezomib ┆ dmso ┆ 24        ┆ t_cd4_cm   ┆ … ┆ 121        ┆ 210        ┆ UBC;UBQLN ┆ ABCA1;ABC │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ 1;TALDO1; ┆ B8;ACAA2; │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ NMT1;BAZ2 ┆ ACADL;ACA │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ A;S…      ┆ DM;…      │
│ bortezomib ┆ dmso ┆ 24        ┆ t_cd4_cm   ┆ … ┆ 73         ┆ 224        ┆ GABARAPL1 ┆ ABCC2;ABC │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ ;NMT1;GSR ┆ C3;ABCD2; │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ ;PTGES3;A ┆ ABHD6;ACO │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ CO2…      ┆ 2;A…      │
└────────────┴──────┴───────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [15]:
hallmark = hallmark.with_columns(
    pl.Series(
        name = 'Cell Type',
        values = [cell_type_update[x] for x in hallmark['aifi_cell_type']]
    ),
    pl.Series(
        name = 'Timepoint',
        values = [timepoint_update[x] for x in hallmark['timepoint'].cast(pl.String)]
    ),
    pl.Series(
        name = 'Treatment',
        values = [treatment_update[x] for x in hallmark['fg']]
    ),
    pl.Series(
        name = 'fg',
        values = [treatment_update[x] for x in hallmark['fg']]
    ),
    pl.Series(
        name = 'bg',
        values = [treatment_update[x] for x in hallmark['bg']]
    ),
    pl.col('NES').cast(pl.Float32),
    pl.col('nomP').cast(pl.Float32),
    pl.col('adjP').cast(pl.Float32)
).rename(
    {'pathway_label': 'pathway',
     'n_leadingEdge': 'n_leading_edge_genes',
     'leadingEdge': 'leading_edge_genes'}
).select(
    ['Cell Type', 'Treatment', 'Timepoint', 'fg', 'bg', 'pathway',
     'NES', 'nomP', 'adjP', 'n_pathway_genes', 'n_leading_edge_genes', 'leading_edge_genes']
)

In [16]:
hallmark.head()

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬──────────┬───────────┬───────────┬───────────┐
│ Cell Type ┆ Treatment ┆ Timepoint ┆ fg        ┆ … ┆ adjP     ┆ n_pathway ┆ n_leading ┆ leading_e │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---      ┆ _genes    ┆ _edge_gen ┆ dge_genes │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f32      ┆ ---       ┆ es        ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆          ┆ i64       ┆ ---       ┆ str       │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆ i64       ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪═══════════╪═══════════╪═══════════╡
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 0.000003 ┆ 236       ┆ 180       ┆ PSMD1;PSM │
│           ┆ b         ┆           ┆ b         ┆   ┆          ┆           ┆           ┆ D14;PSMB2 │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ;PSMD7;PS │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ MA6…      │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 0.003499 ┆ 211       ┆ 142       ┆ PSMD14;TX │
│           ┆ b         ┆           ┆ b         ┆   ┆          ┆           ┆           ┆ NRD1;PSMD │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ 12;PSMC6; │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ SQS…      │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 0.054414 ┆ 58        ┆ 38        ┆ TXNRD1;TX │
│           ┆ b         ┆           ┆ b         ┆   ┆          ┆           ┆           ┆ N;GSR;FTL │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ;PRDX1;GC │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ LM;…      │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 0.026212 ┆ 210       ┆ 121       ┆ UBC;UBQLN │
│           ┆ b         ┆           ┆ b         ┆   ┆          ┆           ┆           ┆ 1;TALDO1; │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ NMT1;BAZ2 │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ A;S…      │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 0.266258 ┆ 224       ┆ 73        ┆ GABARAPL1 │
│           ┆ b         ┆           ┆ b         ┆   ┆          ┆           ┆           ┆ ;NMT1;GSR │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ ;PTGES3;A │
│           ┆           ┆           ┆           ┆   ┆          ┆           ┆           ┆ CO2…      │
└───────────┴───────────┴───────────┴───────────┴───┴──────────┴───────────┴───────────┴───────────┘

In [17]:
out_hallmark = 'output/tcell-vrd_gsea_hallmark_{d}.tsv'.format(d = date.today())
hallmark.write_csv(out_hallmark, separator = '\t')
out_files.append(out_hallmark)

## Reactome GSEA

In [18]:
reactome = pl.read_csv(in_files['reactome'], infer_schema_length=100000, separator = '\t')

In [19]:
reactome.head()

shape: (5, 13)
┌────────────┬──────┬───────────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ fg         ┆ bg   ┆ timepoint ┆ aifi_cell_ ┆ … ┆ n_leadingE ┆ n_pathway_ ┆ leadingEd ┆ pathway_g │
│ ---        ┆ ---  ┆ ---       ┆ type       ┆   ┆ dge        ┆ genes      ┆ ge        ┆ enes      │
│ str        ┆ str  ┆ i64       ┆ ---        ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│            ┆      ┆           ┆ str        ┆   ┆ i64        ┆ i64        ┆ str       ┆ str       │
╞════════════╪══════╪═══════════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ bortezomib ┆ dmso ┆ 24        ┆ t_cd4_cm   ┆ … ┆ 168        ┆ 247        ┆ PSMD1;PSM ┆ AMER1;ANK │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ D14;VCP;U ┆ RD9;ASB1; │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ BC;PSMD11 ┆ ASB10;ASB │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ ;NP…      ┆ 11;…      │
│ bortezomib ┆ dmso ┆ 24        ┆ t_cd4_cm   ┆ … ┆ 106        ┆ 177        ┆ PSMD1;PSM ┆ AAAS;ABCA │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ D14;VCP;U ┆ 1;ABCA12; │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ BC;PSMD11 ┆ ABCA3;ABC │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ ;PS…      ┆ B11…      │
│ bortezomib ┆ dmso ┆ 24        ┆ t_cd4_cm   ┆ … ┆ 94         ┆ 132        ┆ PSMD1;PSM ┆ ABCC1;ABC │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ D14;VCP;U ┆ C3;ABCF2; │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ BC;PSMD11 ┆ ABCG2;AKT │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ ;NP…      ┆ 1;A…      │
│ bortezomib ┆ dmso ┆ 24        ┆ t_cd4_cm   ┆ … ┆ 142        ┆ 199        ┆ PSMD1;PSM ┆ ACTR1A;AJ │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ D14;UBC;P ┆ UBA;AKAP9 │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ SMD11;PSM ┆ ;ALMS1;AU │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ B2;…      ┆ RKA…      │
│ bortezomib ┆ dmso ┆ 24        ┆ t_cd4_cm   ┆ … ┆ 141        ┆ 197        ┆ PSMD1;PSM ┆ ACTR1A;AJ │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ D14;UBC;P ┆ UBA;AKAP9 │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ SMD11;PSM ┆ ;ALMS1;AU │
│            ┆      ┆           ┆            ┆   ┆            ┆            ┆ B2;…      ┆ RKA…      │
└────────────┴──────┴───────────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [20]:
reactome = reactome.with_columns(
    pl.Series(
        name = 'Cell Type',
        values = [cell_type_update[x] for x in reactome['aifi_cell_type']]
    ),
    pl.Series(
        name = 'Timepoint',
        values = [timepoint_update[x] for x in reactome['timepoint'].cast(pl.String)]
    ),
    pl.Series(
        name = 'Treatment',
        values = [treatment_update[x] for x in reactome['fg']]
    ),
    pl.Series(
        name = 'fg',
        values = [treatment_update[x] for x in reactome['fg']]
    ),
    pl.Series(
        name = 'bg',
        values = [treatment_update[x] for x in reactome['bg']]
    ),
    pl.col('NES').cast(pl.Float32),
    pl.col('nomP').cast(pl.Float32),
    pl.col('adjP').cast(pl.Float32)
).rename(
    {'n_leadingEdge': 'n_leading_edge_genes',
     'leadingEdge': 'leading_edge_genes'}
).select(
    ['Cell Type', 'Treatment', 'Timepoint', 'fg', 'bg', 'pathway',
     'NES', 'nomP', 'adjP', 'n_pathway_genes', 'n_leading_edge_genes', 'leading_edge_genes']
)

In [21]:
reactome.head()

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Cell Type ┆ Treatment ┆ Timepoint ┆ fg        ┆ … ┆ adjP      ┆ n_pathway ┆ n_leading ┆ leading_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ _genes    ┆ _edge_gen ┆ edge_gen │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f32       ┆ ---       ┆ es        ┆ es       │
│           ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ i64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 5.8647e-1 ┆ 247       ┆ 168       ┆ PSMD1;PS │
│           ┆ b         ┆           ┆ b         ┆   ┆ 9         ┆           ┆           ┆ MD14;VCP │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ;UBC;PSM │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D11;NP…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 9.0684e-1 ┆ 177       ┆ 106       ┆ PSMD1;PS │
│           ┆ b         ┆           ┆ b         ┆   ┆ 7         ┆           ┆           ┆ MD14;VCP │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ;UBC;PSM │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D11;PS…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 9.1756e-1 ┆ 132       ┆ 94        ┆ PSMD1;PS │
│           ┆ b         ┆           ┆ b         ┆   ┆ 6         ┆           ┆           ┆ MD14;VCP │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ;UBC;PSM │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D11;NP…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 6.2888e-1 ┆ 199       ┆ 142       ┆ PSMD1;PS │
│           ┆ b         ┆           ┆ b         ┆   ┆ 6         ┆           ┆           ┆ MD14;UBC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ;PSMD11; │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ PSMB2;…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 1.5075e-1 ┆ 197       ┆ 141       ┆ PSMD1;PS │
│           ┆ b         ┆           ┆ b         ┆   ┆ 5         ┆           ┆           ┆ MD14;UBC │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ;PSMD11; │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ PSMB2;…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [22]:
out_reactome = 'output/tcell-vrd_gsea_reactome_{d}.tsv'.format(d = date.today())
hallmark.write_csv(out_reactome, separator = '\t')
out_files.append(out_reactome)

## DAP

In [23]:
dap = pl.read_csv(in_files['dap'], infer_schema_length=100000)

In [24]:
dap.head()

shape: (5, 10)
┌────────────────┬──────────────┬────────┬──────────┬───┬───────────┬──────────┬───────────┬─────┐
│ aifi_cell_type ┆ fg           ┆ bg     ┆ seqnames ┆ … ┆ logFC     ┆ adjP     ┆ MeanDiff  ┆ idx │
│ ---            ┆ ---          ┆ ---    ┆ ---      ┆   ┆ ---       ┆ ---      ┆ ---       ┆ --- │
│ str            ┆ str          ┆ str    ┆ str      ┆   ┆ f64       ┆ f64      ┆ f64       ┆ i64 │
╞════════════════╪══════════════╪════════╪══════════╪═══╪═══════════╪══════════╪═══════════╪═════╡
│ t_cd4_cm       ┆ bortezomib_4 ┆ dmso_4 ┆ chr1     ┆ … ┆ 0.762472  ┆ 0.961701 ┆ 0.016549  ┆ 1   │
│ t_cd4_cm       ┆ bortezomib_4 ┆ dmso_4 ┆ chr1     ┆ … ┆ -0.012146 ┆ 0.961701 ┆ -0.002062 ┆ 2   │
│ t_cd4_cm       ┆ bortezomib_4 ┆ dmso_4 ┆ chr1     ┆ … ┆ -0.720519 ┆ 0.961701 ┆ -0.017751 ┆ 3   │
│ t_cd4_cm       ┆ bortezomib_4 ┆ dmso_4 ┆ chr1     ┆ … ┆ -1.176057 ┆ 0.961701 ┆ -0.016888 ┆ 6   │
│ t_cd4_cm       ┆ bortezomib_4 ┆ dmso_4 ┆ chr1     ┆ … ┆ -0.215636 ┆ 0.961701 ┆ -0.040113 ┆ 7   │
└────────────────┴──────────────┴────────┴──────────┴───┴───────────┴──────────┴───────────┴─────┘

In [25]:
dap = dap.with_columns(
    pl.Series(
        name = 'Cell Type',
        values = [cell_type_update[x] for x in dap['aifi_cell_type']]
    ),
    pl.Series(
        name = 'Timepoint',
        values = ['T' + re.sub('.+_','',x) for x in dap['fg']]
    ),
    pl.Series(
        name = 'Treatment',
        values = [treatment_update[re.sub('_.+','',x)] for x in dap['fg']]
    ),
    pl.Series(
        name = 'fg',
        values = [treatment_update[re.sub('_.+','',x)] for x in dap['fg']]
    ),
    pl.Series(
        name = 'bg',
        values = [treatment_update[re.sub('_.+','',x)] for x in dap['bg']]
    ),
    pl.col('MeanDiff').cast(pl.Float32),
    pl.col('adjP').cast(pl.Float32),
    pl.concat_str(
        [pl.col('seqnames'),pl.lit(':'),pl.col('start'),pl.lit('-'),pl.col('end')]
    ).alias('peak')
).select(
    ['Cell Type', 'Treatment', 'Timepoint', 'fg', 'bg', 'peak',
     'MeanDiff', 'adjP']
)

In [26]:
dap.head()

shape: (5, 8)
┌───────────┬────────────┬───────────┬────────────┬──────┬──────────────────┬───────────┬──────────┐
│ Cell Type ┆ Treatment  ┆ Timepoint ┆ fg         ┆ bg   ┆ peak             ┆ MeanDiff  ┆ adjP     │
│ ---       ┆ ---        ┆ ---       ┆ ---        ┆ ---  ┆ ---              ┆ ---       ┆ ---      │
│ str       ┆ str        ┆ str       ┆ str        ┆ str  ┆ str              ┆ f32       ┆ f32      │
╞═══════════╪════════════╪═══════════╪════════════╪══════╪══════════════════╪═══════════╪══════════╡
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ DMSO ┆ chr1:817097-8175 ┆ 0.016549  ┆ 0.961701 │
│           ┆            ┆           ┆            ┆      ┆ 97               ┆           ┆          │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ DMSO ┆ chr1:827316-8278 ┆ -0.002062 ┆ 0.961701 │
│           ┆            ┆           ┆            ┆      ┆ 16               ┆           ┆          │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ DMSO ┆ chr1:844402-8449 ┆ -0.017751 ┆ 0.961701 │
│           ┆            ┆           ┆            ┆      ┆ 02               ┆           ┆          │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ DMSO ┆ chr1:903980-9044 ┆ -0.016888 ┆ 0.961701 │
│           ┆            ┆           ┆            ┆      ┆ 80               ┆           ┆          │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ DMSO ┆ chr1:904495-9049 ┆ -0.040113 ┆ 0.961701 │
│           ┆            ┆           ┆            ┆      ┆ 95               ┆           ┆          │
└───────────┴────────────┴───────────┴────────────┴──────┴──────────────────┴───────────┴──────────┘

In [27]:
out_dap = 'output/tcell-vrd_dap_{d}.csv'.format(d = date.today())
dap.write_csv(out_dap)
out_files.append(out_dap)

## DAM

In [28]:
dam = pl.read_csv(in_files['dam'], infer_schema_length=100000)

In [29]:
dam.tail()

shape: (5, 17)
┌────────────┬────────────┬─────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ aifi_cell_ ┆ fg         ┆ bg      ┆ direction ┆ … ┆ Backgroun ┆ ComparePr ┆ nCompare ┆ CompareFr │
│ type       ┆ ---        ┆ ---     ┆ ---       ┆   ┆ dFrequenc ┆ oportion  ┆ ---      ┆ equency   │
│ ---        ┆ str        ┆ str     ┆ str       ┆   ┆ y         ┆ ---       ┆ i64      ┆ ---       │
│ str        ┆            ┆         ┆           ┆   ┆ ---       ┆ str       ┆          ┆ i64       │
│            ┆            ┆         ┆           ┆   ┆ i64       ┆           ┆          ┆           │
╞════════════╪════════════╪═════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ t_cd8_naiv ┆ lenalidomi ┆ dmso_72 ┆ dn        ┆ … ┆ 9193      ┆ 0.1643286 ┆ 499      ┆ 82        │
│ e          ┆ de_72      ┆         ┆           ┆   ┆           ┆ 57314629  ┆          ┆           │
│ t_cd8_naiv ┆ lenalidomi ┆ dmso_72 ┆ dn        ┆ … ┆ 4096      ┆ 0.0521042 ┆ 499      ┆ 26        │
│ e          ┆ de_72      ┆         ┆           ┆   ┆           ┆ 084168337 ┆          ┆           │
│ t_cd8_naiv ┆ lenalidomi ┆ dmso_72 ┆ dn        ┆ … ┆ 4663      ┆ 0.0601202 ┆ 499      ┆ 30        │
│ e          ┆ de_72      ┆         ┆           ┆   ┆           ┆ 404809619 ┆          ┆           │
│ t_cd8_naiv ┆ lenalidomi ┆ dmso_72 ┆ dn        ┆ … ┆ 3107      ┆ 0.0320641 ┆ 499      ┆ 16        │
│ e          ┆ de_72      ┆         ┆           ┆   ┆           ┆ 28256513  ┆          ┆           │
│ t_cd8_naiv ┆ lenalidomi ┆ dmso_72 ┆ dn        ┆ … ┆ 3107      ┆ 0.0320641 ┆ 499      ┆ 16        │
│ e          ┆ de_72      ┆         ┆           ┆   ┆           ┆ 28256513  ┆          ┆           │
└────────────┴────────────┴─────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [30]:
dam = dam.with_columns(
    pl.Series(
        name = 'Cell Type',
        values = [cell_type_update[x] for x in dam['aifi_cell_type']]
    ),
    pl.Series(
        name = 'Timepoint',
        values = ['T' + re.sub('.+_','',x) for x in dam['fg']]
    ),
    pl.Series(
        name = 'Treatment',
        values = [treatment_update[re.sub('_.+','',x)] for x in dam['fg']]
    ),
    pl.Series(
        name = 'fg',
        values = [treatment_update[re.sub('_.+','',x)] for x in dam['fg']]
    ),
    pl.Series(
        name = 'bg',
        values = [treatment_update[re.sub('_.+','',x)] for x in dam['bg']]
    ),
    pl.col('Enrichment').replace('NA', None).cast(pl.Float32),
    pl.col('CompareProportion').replace('NA', None).cast(pl.Float32),
    pl.col('nomP').cast(pl.Float32),
    pl.col('adjP').cast(pl.Float32)
).rename(
    {'feature': 'motif_id',
     'BackgroundProporition': 'bg_prop',
     'nBackground': 'bg_n',
     'BackgroundFrequency': 'bg_freq',
     'CompareProportion': 'fg_prop',
     'nCompare': 'fg_n',
     'CompareFrequency': 'fg_freq'
    }
).select(
    ['Cell Type', 'Treatment', 'Timepoint', 'fg', 'bg', 'motif_id', 'tf_gene',
     'Enrichment', 'nomP', 'adjP',
     'bg_n', 'bg_freq', 'bg_prop', 'fg_n', 'fg_freq', 'fg_prop']
)

In [31]:
dam.head()

shape: (5, 16)
┌───────────┬────────────┬───────────┬────────────┬───┬──────────┬──────┬─────────┬─────────┐
│ Cell Type ┆ Treatment  ┆ Timepoint ┆ fg         ┆ … ┆ bg_prop  ┆ fg_n ┆ fg_freq ┆ fg_prop │
│ ---       ┆ ---        ┆ ---       ┆ ---        ┆   ┆ ---      ┆ ---  ┆ ---     ┆ ---     │
│ str       ┆ str        ┆ str       ┆ str        ┆   ┆ f64      ┆ i64  ┆ i64     ┆ f32     │
╞═══════════╪════════════╪═══════════╪════════════╪═══╪══════════╪══════╪═════════╪═════════╡
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.068548 ┆ 0    ┆ 0       ┆ null    │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.168745 ┆ 0    ┆ 0       ┆ null    │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.145249 ┆ 0    ┆ 0       ┆ null    │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.049205 ┆ 0    ┆ 0       ┆ null    │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.082049 ┆ 0    ┆ 0       ┆ null    │
└───────────┴────────────┴───────────┴────────────┴───┴──────────┴──────┴─────────┴─────────┘

In [32]:
out_dam = 'output/tcell-vrd_dam_{d}.csv'.format(d = date.today())
dam.write_csv(out_dam)
out_files.append(out_dam)

## DEP

In [33]:
dep = pl.read_csv(in_files['dep'], infer_schema_length=100000)

In [34]:
dep.head()

shape: (5, 16)
┌────────────────┬───────────┬────────────┬──────┬───┬──────────┬──────────┬──────────┬───────────┐
│ aifi_cell_type ┆ timepoint ┆ fg         ┆ bg   ┆ … ┆ bg_mean  ┆ fc       ┆ adjP     ┆ logFC     │
│ ---            ┆ ---       ┆ ---        ┆ ---  ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str            ┆ i64       ┆ str        ┆ str  ┆   ┆ f64      ┆ f64      ┆ f64      ┆ f64       │
╞════════════════╪═══════════╪════════════╪══════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ t_cd4_cm       ┆ 4         ┆ bortezomib ┆ dmso ┆ … ┆ 0.121879 ┆ 1.04239  ┆ 0.795736 ┆ 0.059894  │
│ t_cd4_cm       ┆ 4         ┆ bortezomib ┆ dmso ┆ … ┆ 0.513305 ┆ 0.996711 ┆ 0.983653 ┆ -0.004753 │
│ t_cd4_cm       ┆ 4         ┆ bortezomib ┆ dmso ┆ … ┆ 0.035874 ┆ 0.864311 ┆ 0.507491 ┆ -0.210377 │
│ t_cd4_cm       ┆ 4         ┆ bortezomib ┆ dmso ┆ … ┆ 0.10714  ┆ 1.049994 ┆ 0.743134 ┆ 0.070382  │
│ t_cd4_cm       ┆ 4         ┆ bortezomib ┆ dmso ┆ … ┆ 0.285113 ┆ 1.031952 ┆ 0.694816 ┆ 0.045376  │
└────────────────┴───────────┴────────────┴──────┴───┴──────────┴──────────┴──────────┴───────────┘

In [36]:
dep = dep.with_columns(
    pl.Series(
        name = 'Cell Type',
        values = [cell_type_update[x] for x in dep['aifi_cell_type']]
    ),
    pl.Series(
        name = 'Timepoint',
        values = [timepoint_update[x] for x in dep['timepoint'].cast(pl.String)]
    ),
    pl.Series(
        name = 'Treatment',
        values = [treatment_update[x] for x in dep['fg']]
    ),
    pl.Series(
        name = 'fg',
        values = [treatment_update[x] for x in dep['fg']]
    ),
    pl.Series(
        name = 'bg',
        values = [treatment_update[x] for x in dep['bg']]
    ),
    pl.col('logFC').cast(pl.Float32),
    pl.col('nomP').cast(pl.Float32),
    pl.col('adjP').cast(pl.Float32)
).rename(
    {'n_downsample': 'n_sample'}
).select(
    ['Cell Type', 'Treatment', 'Timepoint', 'fg', 'bg', 'feature',
     'n_sample', 'mean', 'logFC', 'nomP', 'adjP']
)

In [37]:
dep.head()

shape: (5, 11)
┌───────────┬────────────┬───────────┬────────────┬───┬──────────┬───────────┬──────────┬──────────┐
│ Cell Type ┆ Treatment  ┆ Timepoint ┆ fg         ┆ … ┆ mean     ┆ logFC     ┆ nomP     ┆ adjP     │
│ ---       ┆ ---        ┆ ---       ┆ ---        ┆   ┆ ---      ┆ ---       ┆ ---      ┆ ---      │
│ str       ┆ str        ┆ str       ┆ str        ┆   ┆ f64      ┆ f32       ┆ f32      ┆ f32      │
╞═══════════╪════════════╪═══════════╪════════════╪═══╪══════════╪═══════════╪══════════╪══════════╡
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.124462 ┆ 0.059894  ┆ 0.440789 ┆ 0.795736 │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.51246  ┆ -0.004753 ┆ 0.912887 ┆ 0.983653 │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.03344  ┆ -0.210377 ┆ 0.157287 ┆ 0.507491 │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.109818 ┆ 0.070382  ┆ 0.352611 ┆ 0.743133 │
│ CD4 CM    ┆ Bortezomib ┆ T4        ┆ Bortezomib ┆ … ┆ 0.289668 ┆ 0.045376  ┆ 0.306351 ┆ 0.694816 │
└───────────┴────────────┴───────────┴────────────┴───┴──────────┴───────────┴──────────┴──────────┘

In [38]:
out_dep = 'output/tcell-vrd_dep_{d}.csv'.format(d = date.today())
dep.write_csv(out_dep)
out_files.append(out_dep)

## DGM

Format as for GSEA enrichment for use in data app visualization

In [39]:
dgm = pl.read_csv(in_files['dgm'], infer_schema_length=100000)

In [40]:
dgm['direction'].value_counts()

shape: (3, 2)
┌───────────┬───────┐
│ direction ┆ count │
│ ---       ┆ ---   │
│ str       ┆ u32   │
╞═══════════╪═══════╡
│ all       ┆ 10840 │
│ up        ┆ 10840 │
│ dn        ┆ 10840 │
└───────────┴───────┘

In [41]:
dgm.head()

shape: (5, 15)
┌────────────┬───────────┬─────────────┬───────────┬───┬──────┬───────────┬─────────────┬──────────┐
│ treatment  ┆ timepoint ┆ aifi_cell_t ┆ direction ┆ … ┆ n_ol ┆ nomP      ┆ ol_genes    ┆ adjP     │
│ ---        ┆ ---       ┆ ype         ┆ ---       ┆   ┆ ---  ┆ ---       ┆ ---         ┆ ---      │
│ str        ┆ i64       ┆ ---         ┆ str       ┆   ┆ i64  ┆ f64       ┆ str         ┆ f64      │
│            ┆           ┆ str         ┆           ┆   ┆      ┆           ┆             ┆          │
╞════════════╪═══════════╪═════════════╪═══════════╪═══╪══════╪═══════════╪═════════════╪══════════╡
│ bortezomib ┆ 24        ┆ t_cd4_cm    ┆ all       ┆ … ┆ 341  ┆ 0.083555  ┆ ABAT;ABHD4; ┆ 0.179853 │
│            ┆           ┆             ┆           ┆   ┆      ┆           ┆ ABI1;ABLIM1 ┆          │
│            ┆           ┆             ┆           ┆   ┆      ┆           ┆ ;ACAP2;A…   ┆          │
│ bortezomib ┆ 24        ┆ t_cd4_cm    ┆ all       ┆ … ┆ 104  ┆ 0.061935  ┆ ABLIM1;ACVR ┆ 0.138343 │
│            ┆           ┆             ┆           ┆   ┆      ┆           ┆ 1C;ADAM19;A ┆          │
│            ┆           ┆             ┆           ┆   ┆      ┆           ┆ HNAK;ALS…   ┆          │
│ bortezomib ┆ 24        ┆ t_cd4_cm    ┆ all       ┆ … ┆ 193  ┆ 0.001451  ┆ ABAT;ABI1;A ┆ 0.005219 │
│            ┆           ┆             ┆           ┆   ┆      ┆           ┆ CO2;ACTB;AD ┆          │
│            ┆           ┆             ┆           ┆   ┆      ┆           ┆ AM19;ADH…   ┆          │
│ bortezomib ┆ 24        ┆ t_cd4_cm    ┆ all       ┆ … ┆ 190  ┆ 4.9349e-7 ┆ ACAP2;ADAM1 ┆ 0.000005 │
│            ┆           ┆             ┆           ┆   ┆      ┆           ┆ 9;AHNAK;AIM ┆          │
│            ┆           ┆             ┆           ┆   ┆      ┆           ┆ 2;ALS2;A…   ┆          │
│ bortezomib ┆ 24        ┆ t_cd4_cm    ┆ all       ┆ … ┆ 96   ┆ 0.000045  ┆ ABHD3;ACAP2 ┆ 0.000253 │
│            ┆           ┆             ┆           ┆   ┆      ┆           ┆ ;ADAM19;ADG ┆          │
│            ┆           ┆             ┆           ┆   ┆      ┆           ┆ RE5;AGTP…   ┆          │
└────────────┴───────────┴─────────────┴───────────┴───┴──────┴───────────┴─────────────┴──────────┘

In [42]:
dgm = dgm.with_columns(
    pl.Series(
        name = 'Cell Type',
        values = [cell_type_update[x] for x in dgm['aifi_cell_type']]
    ),
    pl.Series(
        name = 'Timepoint',
        values = [timepoint_update[x] for x in dgm['timepoint'].cast(pl.String)]
    ),
    pl.Series(
        name = 'Treatment',
        values = [treatment_update[x] for x in dgm['treatment']]
    ),
    pl.Series(
        name = 'fg',
        values = [treatment_update[x] for x in dgm['treatment']]
    ),
    pl.lit('DMSO').alias('bg'),
    pl.col('tf_logFC').replace('NA', None).cast(pl.Float32),
    pl.col('nomP').cast(pl.Float32),
    pl.col('adjP').cast(pl.Float32)
).rename(
    {'n_all_genes': 'n_genes',
     'n_all_genes': 'n_tested_genes',
     'n_motif_genes': 'n_tested_genes_near_motif',
     'n_ol': 'n_deg_near_motif',
     'ol_genes': 'deg_near_motif',
     'direction': 'deg_direction'}
).select(
    ['Cell Type', 'Treatment', 'Timepoint', 'fg', 'bg', 'deg_direction',
     'motif_id', 'tf_gene', 'tf_logFC', 'tf_adjP',
     'n_tested_genes', 'n_tested_genes_near_motif', 'n_deg', 'n_deg_near_motif',
     'nomP', 'adjP', 'deg_near_motif']
)

In [43]:
dgm.head()

shape: (5, 17)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ Cell Type ┆ Treatment ┆ Timepoint ┆ fg        ┆ … ┆ n_deg_nea ┆ nomP      ┆ adjP     ┆ deg_near_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ r_motif   ┆ ---       ┆ ---      ┆ motif     │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ ---       ┆ f32       ┆ f32      ┆ ---       │
│           ┆           ┆           ┆           ┆   ┆ i64       ┆           ┆          ┆ str       │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 341       ┆ 0.083555  ┆ 0.179853 ┆ ABAT;ABHD │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆          ┆ 4;ABI1;AB │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ LIM1;ACAP │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 2;A…      │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 104       ┆ 0.061935  ┆ 0.138343 ┆ ABLIM1;AC │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆          ┆ VR1C;ADAM │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 19;AHNAK; │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ ALS…      │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 193       ┆ 0.001451  ┆ 0.005219 ┆ ABAT;ABI1 │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆          ┆ ;ACO2;ACT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ B;ADAM19; │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ ADH…      │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 190       ┆ 4.9349e-7 ┆ 0.000005 ┆ ACAP2;ADA │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆          ┆ M19;AHNAK │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ ;AIM2;ALS │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ 2;A…      │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 96        ┆ 0.000045  ┆ 0.000253 ┆ ABHD3;ACA │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆          ┆ P2;ADAM19 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ ;ADGRE5;A │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆          ┆ GTP…      │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [44]:
out_dgm = 'output/tcell-vrd_dgm_{d}.csv'.format(d = date.today())
dgm.write_csv(out_dgm)
out_files.append(out_dgm)

To treat DGM like pathways, we'll compute an enrichment based on the background expectation of `frac_expected = n_tested_genes_near_motif / n_tested_genes`. We'll then use `frac_deg = n_deg_near_motif / n_deg` as the enriched proportion. `frac_deg / frac_expected` will be our enrichment score, which we'll add to the "NES" column for consistency with pathway results.

We'll also use just the up- and down-regulated deg sets, and assign a negative score to the down-regulated DEG sets so that they align with GSEA analyses.

In [45]:
dgm_pathway_structure = dgm.filter(
    pl.col('deg_direction').is_in(['up','dn'])
).with_columns(
    (pl.col('n_tested_genes_near_motif') / pl.col('n_tested_genes')).alias('frac_expected'),
    (pl.col('n_deg_near_motif') / pl.col('n_deg')).alias('frac_deg')
).with_columns(
    pl.when(
        pl.col('deg_direction') == 'up'
    ).then(
        pl.col('frac_deg') / pl.col('frac_expected')
    ).otherwise(
        -1 * pl.col('frac_deg') / pl.col('frac_expected')
    ).alias('NES')
).rename(
    {'motif_id': 'pathway',
     'n_deg': 'n_pathway_genes',
     'n_deg_near_motif': 'n_leading_edge_genes',
     'deg_near_motif': 'leading_edge_genes'
    }
).select(
    ['Cell Type', 'Treatment', 'Timepoint', 'fg', 'bg', 'pathway',
     'NES', 'nomP', 'adjP', 'n_pathway_genes', 'n_leading_edge_genes', 'leading_edge_genes']
)

In [46]:
dgm_pathway_structure.filter(pl.col('adjP') < 0.05).filter(pl.col('NES') < 0).head(20)

shape: (20, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ Cell Type ┆ Treatment ┆ Timepoint ┆ fg        ┆ … ┆ adjP      ┆ n_pathway ┆ n_leading ┆ leading_ │
│ ---       ┆ ---       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ _genes    ┆ _edge_gen ┆ edge_gen │
│ str       ┆ str       ┆ str       ┆ str       ┆   ┆ f32       ┆ ---       ┆ es        ┆ es       │
│           ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆ ---       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ i64       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 0.002904  ┆ 200       ┆ 145       ┆ ABLIM1;A │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆           ┆ CTB;ACVR │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 1C;ADAM1 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 9;ADGR…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 0.00003   ┆ 200       ┆ 60        ┆ ABLIM1;A │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆           ┆ CVR1C;AD │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ AM19;AHN │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ AK;ANK…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 4.0011e-7 ┆ 200       ┆ 98        ┆ ACTB;ADA │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆           ┆ M19;ANK3 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ;ANTXR2; │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ARHGAP…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 2.0831e-1 ┆ 200       ┆ 98        ┆ ADAM19;A │
│           ┆ b         ┆           ┆ b         ┆   ┆ 0         ┆           ┆           ┆ HNAK;ANK │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 3;ANTXR2 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ;ARHGA…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 7.8048e-8 ┆ 200       ┆ 55        ┆ ADAM19;A │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆           ┆ DGRE5;AN │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ K3;ANTXR │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 2;ARL4…  │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 1.9108e-7 ┆ 200       ┆ 99        ┆ ACTB;AHN │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆           ┆ AK;ANK3; │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ANTXR2;A │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ RHGAP1…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 7.2664e-1 ┆ 200       ┆ 78        ┆ ACTB;ADA │
│           ┆ b         ┆           ┆ b         ┆   ┆ 2         ┆           ┆           ┆ M19;ADGR │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ E5;AHNAK │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ;ANK3;…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 0.000005  ┆ 200       ┆ 49        ┆ ADGRE5;A │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆           ┆ HNAK;ANT │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ XR2;ARHG │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ AP15;A…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 0.000001  ┆ 200       ┆ 50        ┆ AHNAK;AN │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆           ┆ TXR2;ARI │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ D5B;ARL4 │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ C;BCL2…  │
│ CD4 CM    ┆ Bortezomi ┆ T24       ┆ Bortezomi ┆ … ┆ 0.000023  ┆ 200       ┆ 35        ┆ ADAM19;A │
│           ┆ b         ┆           ┆ b         ┆   ┆           ┆           ┆           ┆ NTXR2;AR │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ID5B;ARL │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 4C;BCL…  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [47]:
out_gsea_dgm = 'output/tcell-vrd_gsea_dgm_{d}.csv'.format(d = date.today())
dgm_pathway_structure.write_csv(out_gsea_dgm)
out_files.append(out_gsea_dgm)

## Upload results to HISE

In [48]:
study_space_uuid = '40df6403-29f0-4b45-ab7d-f46d420c422e'
title = 'VRd TEA-seq formatted differential tables {d}'.format(d = date.today())

In [49]:
search_id = element_id()
search_id

'gold-neptunium-aluminum'

In [50]:
in_files = list(in_uuids.values())

In [51]:
in_files

['a134530f-9ac4-4d37-bf01-97c73bf1ce24',
 '4f05f2a0-59d2-4d04-b948-70d541613e71',
 'ad8d7320-399c-41ff-8b2f-b840d8eae324',
 '681e1f11-708c-4ab4-8ed0-87ef895df152',
 'ad10c6d0-0aad-490f-a82c-6bf7ce67cd58',
 '38b59e4a-3c87-460d-b3e2-fd5ed62e7264',
 '06039bda-26a0-4a51-85b4-f2b5aedcdf74']

In [52]:
out_files

['output/tcell-vrd_deg_2026-06-15.csv',
 'output/tcell-vrd_gsea_hallmark_2026-06-15.tsv',
 'output/tcell-vrd_gsea_reactome_2026-06-15.tsv',
 'output/tcell-vrd_dap_2026-06-15.csv',
 'output/tcell-vrd_dam_2026-06-15.csv',
 'output/tcell-vrd_dep_2026-06-15.csv',
 'output/tcell-vrd_dgm_2026-06-15.csv',
 'output/tcell-vrd_gsea_dgm_2026-06-15.csv']

In [53]:
import session_info
session_info.show()

In [54]:
hisepy.upload_files(
    files = out_files,
    study_space_id = study_space_uuid,
    title = title,
    input_file_ids = in_files,
    destination = search_id
)

2026-06-15 21:28:28,960 INFO [hisepy.logging:175] logging 14664 139138472589120 Calling upload_files

Please provide input of comma separated sample ids for the files being uploaded. If you do not have any sample ids, press enter:

2026-06-15 21:28:32,433 INFO [hisepy.logging:175] logging 14664 139138472589120 Calling get_default_store
2026-06-15 21:28:34,201 INFO [hisepy.logging:208] logging 14664 139138472589120 Finished get_default_store, success=True, time_elapsed=0.403s
2026-06-15 21:28:48,616 INFO [hisepy.logging:208] logging 14664 139138472589120 Finished upload_files, success=True, time_elapsed=18.208s

{'Message': 'General Okay-ness',
 'VisualizationId': '00000000-0000-0000-0000-000000000000',
 'AbstractionId': '00000000-0000-0000-0000-000000000000',
 'TraceId': '27b4720f-0346-427d-a951-5b2ebb826248',
 'ProcessId': '3adf67dd-552e-4de9-a800-ce247fc9e28a',
 'WorkflowId': '5ae3401e-9581-4f32-a6c9-b6caf04d3e98',
 'FileIds': ['3279167f-a71c-442b-a325-2f778b4b07a1',
  '72224905-7a0e-439b-ae55-b582b72a2a69',
  'c33f14e3-f884-4272-b6c9-cf3f9b3a05c0',
  'cb748e0a-076f-46dc-9a9e-d24541f2c3ef',
  '6565ea13-2b82-40bb-b150-e42324c7144a',
  'c8c3b24b-286d-462d-ad88-206d78fc6b7f',
  '8276b63f-2c20-47ca-8dc7-f9b6285933b4',
  '5b1726a5-a49e-4882-a8a7-caa7c15fcfa1']}